### ISSUE TITLE
Nullreff on pristine install

### ISSUE THREAD

**Issue by KronicOffender** [linuxgurugamer/WasdEditorCameraContinued#1]
I noticed that my career save was throwing null reffs like it was it's job. So I went through the mods one by one and this mod was the last one. When I deleted it the null reffs stopped. So I slapped it into my pristine Steam install and sure enough it null reffed. I've uploaded the log file here as opposed to the forum. 
[KSP.txt](https://github.com/linuxgurugamer/WasdEditorCameraContinued/files/36142/KSP.txt)

**Comment by linuxgurugamer** [comment]
Thank you.

Two questions:

What version of WASD did you install?
How did you install it?

If you didn't install 0.5.1, please install that and try again.

Thanks


JBB

**Comment by linuxgurugamer** [comment]
Also, which log file?  KSP.log, or KSP_Data/output_log.txt?

**Comment by linuxgurugamer** [comment]
I've been able to duplicate it, will get a fix today

**Comment by KronicOffender** [comment]
By the way - thank you for the work you do!!

**Comment by linuxgurugamer** [comment]
The duplication seemed to be a fluke, I can't reproduce it.   Can you please send me a specific list of steps/actions which reproduce this?  Include mouse movements, if you can.
Thanks

**Comment by linuxgurugamer** [comment]
I think I have it.  Please confirm this:

1. Start the game
2.  Go into the Editor, create a simple ship (1 part is enough).
3.  Quit the game via the Task Manager.
Check the log file, you won't see the exceptions.

Now, repeat the above, only this time, exit the editor to the space center, then exit the game
Check the log, you will see the exceptions

please confirm, I know what this problem is

**Comment by KronicOffender** [comment]
Yes. I just finished duplicating the steps you outline and got the same results.

**Comment by linuxgurugamer** [comment]
ok.  Fixed, will be uploading new version in a minute or two.

Thanks for the help

**Comment by linuxgurugamer** [comment]
Uploaded!  0.5.2, will not be in CKAN for a few hours because CKAN takes time to update.
