### ISSUE TITLE
Linux: Cursor stays hidden after rotating the camera. 

### ISSUE THREAD

**Issue by alismatales** [linuxgurugamer/WasdEditorCameraContinued#11]
https://github.com/linuxgurugamer/WasdEditorCameraContinued/blob/46d5672d8451e01f2f38dc1c4a2543a99bf17cbf/src/WasdEditorCameraBehaviour.cs#L504

On linux the cursor disappears in the VAB/SPH when rotating the camera with a middle/right click.

Modifying UnlockCursor() solves this: 

`public void UnlockCursor()`
 `       {`
  `          Cursor.lockState = CursorLockMode.None;`
   `         Cursor.visible = true;`
    `    }`

**Comment by linuxgurugamer** [comment]
Did you try this on the up-to-date version?  YOu seem to be referencing a commit from nearly 2 years ago

**Comment by linuxgurugamer** [comment]
Both issues?  You only mentioned one above

**Comment by linuxgurugamer** [comment]
Oh, never mind, I see the other one

**Comment by linuxgurugamer** [comment]
fixed in latest release
