### ISSUE TITLE
[Feature Request]: Toggle stock VAB/SPH Camera mode 

### ISSUE THREAD

**Issue by deimos790** [linuxgurugamer/WasdEditorCameraContinued#5]
Feature request to toggle default stock camera mod in the editor (VAB/SPH modes).

From:
http://forum.kerbalspaceprogram.com/index.php?/topic/121386-wasd-editor-camera-continued/&do=findComment&comment=2692384

**Comment by MuricanJeb** [comment]
You already can...
Press '5'
