### ISSUE TITLE
[bug] Switch VAB/SPH button (ksp 1.4)

### ISSUE THREAD

**Issue by yalov** [linuxgurugamer/WasdEditorCameraContinued#8]
way to replicate the bug:

 * open VAB
 * build some vessel
 * move using wasd
 * switch to SPH using the button, 
 * move using wasd

Now a view is jumping when you trying to add a new part or rotate a view using mouse right-click

**Comment by yalov** [comment]
@linuxgurugamer you encountered the bug on your stream 20181015, when was building a shuttle.
The "switch editor" button works ok without wasd-camera mod

**Comment by linuxgurugamer** [comment]
ok, ok.  And I think I know what's going on, thank you

**Comment by linuxgurugamer** [comment]
Thanks, just released a fix
